export const destinations: Record<string, string> = {
  'Experience LAMID ONE': '/start',
  'See How It Works': '/how-it-works',
  'Explore the Companion': '/product/companion',
  'Experience the Companion': '/os/companion',
  'View Plans': '/pricing',
  'Responsible AI': '/responsible-ai',
  'Create Account': '/signup',
  'Sign In': '/login',
  'Read Our Story': '/about/story',
  'Choose Your Context': '/start',
  'See the Operating Model': '/how-it-works',
  'Explore Integrations': '/integrations',
  'View SDKs': '/developers/sdks',
  'Read Webhook Docs': '/developers/webhooks',
  'Search Help': '/help',
  'Start the Guide': '/help/getting-started',
  'Browse Account Help': '/help/account',
  'Contact Security': '/contact',
  'Contact Accessibility': '/contact',
  'See the OS in Action': '/demo',
  'See LAMID ONE in Action': '/demo',
  'Start the Demo': '/start',
  'See Workflow Capability': '/product/workflows',
  'Explore LAMID ONE for Organizations': '/product/organizations',
  'Start With Clarity': '/how-it-works/clarity',
  'Experience Clarity': '/os/clarity',
  'Explore Capability': '/how-it-works/capability',
  'Build Your Rhythm': '/how-it-works/rhythm',
  'Explore the Rhythm': '/how-it-works/rhythm',
  'Start With LAMID ONE': '/start?context=Individual',
  'Explore LAMID ONE for Professionals': '/start?context=Professional',
  'Explore LAMID ONE for Creators': '/start?context=Creator',
  'Explore LAMID ONE for Founders': '/start?context=Founder',
  'Explore LAMID ONE for Teams': '/start?context=Team',
  'Explore LAMID ONE for SMEs': '/start?context=SME',
  'Explore LAMID ONE for Enterprise': '/enterprise',
  'Explore LAMID ONE for Institutions': '/enterprise',
  'Request an Organizational Demo': '/demo/request',
  'Talk to Our Team': '/enterprise/contact',
  Security: '/security',
  'Privacy & Data': '/trust/privacy',
  Governance: '/trust/governance',
  'Read Our AI Principles': '/responsible-ai',
  'View Data Controls': '/os/settings/privacy',
  'Explore Enterprise Platform & Deployment': '/enterprise',
  'View Pricing': '/pricing',
  'Request a Conversation': '/enterprise/contact',
  'Explore Resources': '/resources',
  'Browse Insights': '/insights',
  'Browse Guides': '/guides',
  'Browse Case Studies': '/case-studies',
  'Explore Research': '/research',
  'Browse Product Guides': '/help/product',
  'Contact Support': '/support',
  'Read the Developer Docs': '/developers',
  'View API Reference': '/developers/api',
  'View Changelog': '/developers/changelog',
  'Explore LAMID ONE': '/product',
  'Explore Careers': '/careers',
  'Contact Media': '/press',
  'Continue to Capability': '/os/capability',
  'Continue to Consistency': '/os/consistency',
  'Enter LAMID ONE': '/os',
  'Continue to LAMID ONE': '/os',
  'Send Inquiry': 'mailto:hp@lamidconsulting.com',
  'Find Expertise': '/start',
  'Become an Expert': '/start',
  'Start an Expert Match': '/start',
  'Explore Experts': '/start',
  'View Verification Principles': '/trust/governance',
  'Strengthen Capability': '/how-it-works/capability',
  'Apply to Join the Expert Network': '/start',
};
