import { test } from 'node:test';
import assert from 'node:assert/strict';
import { detailLines } from '../src/app/pdf.mjs';

test('an invoice PDF shows no internal record identifiers or tool method', () => {
  const run = {
    agent_id: 'invoice-generator',
    output: JSON.stringify({
      response: 'Invoice INV-2026-0001',
      evidence: {
        milestoneId: '5b1c2d3e-0000-4000-8000-000000000000',
        invoiceNumber: 'INV-2026-0001',
        amount: 300,
        currency: 'USD',
        method: 'deterministic-calculation',
      },
    }),
  };
  assert.deepEqual(detailLines(run), []);
});

test('other generated documents keep their evidence details', () => {
  const run = {
    agent_id: 'proposal-drafter',
    output: JSON.stringify({
      response: 'Draft',
      evidence: { jobId: 'job-1', method: 'template-only' },
    }),
  };
  assert.deepEqual(detailLines(run), ['jobId: job-1', 'method: template-only']);
});

test('an invoice footer carries no internal tool name or run id', async () => {
  const { footerLine } = await import('../src/app/pdf.mjs');
  const run = { id: 'run-123', agent_id: 'invoice-generator', output: '{}' };
  assert.equal(footerLine(run), 'Generated with LAMID ONE');
  const draft = { id: 'run-456', agent_id: 'proposal-drafter', output: '{}' };
  assert.equal(footerLine(draft), 'Generated by LAMID ONE — proposal-drafter — run run-456');
});
