/** Where each of the original 248 engine codes went in the standards review (see catalog.mjs).
 * verdict: KEEP | REBUILD | MERGE (run as the target tool) | VIEW | CONTENT | RETIRE (no longer offered). */
// verdicts: KEEP (works and matches a standard), REBUILD (same tool, change how it works),
// MERGE (fold into the target), VIEW (make it a free summary view built from other results),
// CONTENT (a library or template, not a paid tool), RETIRE (no recognised method; remove).
const m = (verdict, target, note = '') => ({ verdict, target, note });
export const MAP = {
  S01: m(
    'MERGE',
    'T01',
    '“Reputation” and “Market Recognition” need outside data the user does not have.',
  ),
  S02: m('MERGE', 'T01'),
  S03: m(
    'MERGE',
    'T02',
    'Contradictions show up by comparing actual goals, budgets and initiatives, not by rating “Internal Coherence”.',
  ),
  S04: m('MERGE', 'T02'),
  S05: m('MERGE', 'T12'),
  S06: m(
    'REBUILD',
    'T04',
    'A tracker needs objectives and progress figures. Today it is four 0–5 ratings.',
  ),
  S07: m('MERGE', 'T05', '“Impact Area” rated 0–5 is not a scan; PESTLE lists the actual factors.'),
  S08: m(
    'REBUILD',
    'T26',
    'Its dimensions are already Lewin’s driving and resisting forces. Make it the real method.',
  ),
  S09: m(
    'REBUILD',
    'T03',
    'Ranking needs the priorities themselves. The weighted-selection calculator already exists.',
  ),
  S10: m('MERGE', 'T03'),
  S11: m('MERGE', 'T05', 'Response speed is measurable: days from first signal to decision.'),
  S12: m('MERGE', 'T01', 'Cannot project a trajectory from four ratings.'),

  R01: m('MERGE', 'T12'),
  R02: m('MERGE', 'T06'),
  R03: m(
    'REBUILD',
    'T07',
    'Use control-chart rules to flag drift; a straight trend line misses it or raises false alarms.',
  ),
  R04: m('MERGE', 'T07'),
  R05: m(
    'REBUILD',
    'T09',
    'Needs capacity and demand per team. Today it trends cycle time and meeting load.',
  ),
  R06: m('MERGE', 'T08'),
  R07: m('MERGE', 'T12'),
  R08: m('MERGE', 'T08'),
  R09: m('MERGE', 'T02'),
  R10: m('MERGE', 'T08'),
  R11: m('MERGE', 'T08', '“Real-time” is not true: values are typed in by hand.'),
  R12: m(
    'MERGE',
    'T06',
    'One dimension is named “Strategy Execution Tracker”, which is another tool’s name (copy error).',
  ),
  R13: m('MERGE', 'T45', 'Engagement is measured by asking staff, not by trending cycle time.'),
  R14: m('MERGE', 'T06', '“Real-time pulse” is not true: values are typed in by hand.'),
  R15: m('MERGE', 'T12'),
  R16: m('MERGE', 'T12'),
  R17: m(
    'MERGE',
    'T10',
    'What sets the pace is the constraint, which Theory of Constraints finds.',
  ),
  R18: m('MERGE', 'T31', 'Culture fit is not a time series.'),
  R19: m('RETIRE', '', 'Dimensions such as “Structural Rhythm Field” have no measurable meaning.'),
  R20: m('VIEW', 'T06', 'A department filter on flow metrics, not a separate tool.'),
  R21: m('VIEW', 'T06', 'A business-unit filter on flow metrics.'),
  R22: m('VIEW', 'T06', 'An enterprise roll-up of flow metrics.'),
  R23: m('MERGE', 'T07'),
  R24: m('MERGE', 'T07', 'History belongs to every series, not to a separate tool.'),
  R25: m(
    'REBUILD',
    'T11',
    'Trend statistics cannot find a root cause; its dimensions (“Founding Rhythm Origin”) do not either.',
  ),
  R26: m('MERGE', 'T17'),
  R27: m(
    'MERGE',
    'T09',
    'The sustainable pace is a utilisation band, found from capacity and demand.',
  ),
  R28: m(
    'MERGE',
    'T12',
    'Owner and standard per cycle is a field in the operating rhythm register.',
  ),
  R29: m('VIEW', '', 'Executive summary built from other results.'),
  R30: m('VIEW', '', 'Enterprise summary built from other results.'),

  C02: m('MERGE', 'T10', 'Same name as P22.'),
  C03: m('VIEW', '', 'A single “CORE” score; summarise results the customer already has.'),
  C04: m('VIEW', 'T50'),
  C05: m('VIEW', 'T06'),
  C06: m(
    'REBUILD',
    'T63',
    'Runs the roadmap sequencer, but its purpose is assessing operating-model fit.',
  ),
  C07: m('MERGE', 'T02'),
  C08: m(
    'REBUILD',
    'T49',
    'Dimensions (sponsorship, adoption, resistance, sustainment) map onto published change-readiness research; anchor the answers.',
  ),
  C09: m('VIEW', '', 'Board-level summary built from other results.'),

  Q01: m('MERGE', 'T19', 'A map of decisions needs the list of decisions.'),
  Q02: m(
    'REBUILD',
    'T19',
    '“Stalled” and “Committed” decisions are counts to compute from records, not things to rate 0–5.',
  ),
  Q03: m(
    'KEEP',
    'T22',
    'Real calculation (expected value, regret, value of information). Rename: it compares options, it does not simulate paths.',
  ),
  Q04: m(
    'MERGE',
    'T22',
    'Probability-weighted value is exactly what the scenario calculator does.',
  ),
  Q05: m(
    'REBUILD',
    'T23',
    'Uses the expected-value calculator; timing needs cost of delay against the value of waiting.',
  ),
  Q06: m('KEEP', 'T24', 'Real calculation. Rename to “Priority Conflict Check”.'),
  Q07: m('MERGE', 'T19', 'Checking against past decisions needs the past decisions.'),
  Q08: m(
    'MERGE',
    'T19',
    'Rationale, owner and definition of done are fields in the decision record.',
  ),
  Q09: m(
    'REBUILD',
    'T21',
    'Rates “Selection Bias Patterns” instead of scoring the options. The selection calculator exists.',
  ),
  Q10: m('MERGE', 'T21'),
  Q11: m('MERGE', 'T22'),
  Q12: m('MERGE', 'T22'),
  Q13: m('REBUILD', 'T11', 'Dimensions are “Identity-Origin Decisions” etc., not a cause chain.'),
  Q14: m('MERGE', 'T17'),
  Q15: m(
    'REBUILD',
    'T28',
    'Leading indicators need values and thresholds, not a “Signal Clarity” rating.',
  ),
  Q16: m('MERGE', 'T19', 'Recurrence is counted from the register.'),
  Q17: m('MERGE', 'T25'),
  Q18: m('MERGE', 'T24'),
  Q19: m(
    'RETIRE',
    '',
    'No recognised method; “Fear-Driven Tone Detection” cannot be self-rated reliably.',
  ),
  Q20: m('RETIRE', '', 'Describes a Companion feature, not a tool.'),
  Q21: m(
    'KEEP',
    'T21',
    'Real calculation. Rename: it scores options; it does not build reusable frameworks.',
  ),
  Q22: m('MERGE', 'T20'),
  Q23: m('MERGE', 'T20'),
  Q24: m('MERGE', 'T22', 'Runs the expected-value calculator under a “diagnostic” name.'),
  Q25: m('MERGE', 'T30', 'Patterns come from reviewing past decisions against outcomes.'),
  Q26: m('RETIRE', '', '“Decision signature” has no recognised method.'),
  Q27: m(
    'REBUILD',
    'T35',
    'Hit rate is measured with calibration scores, not self-rating. Profiling individuals also needs HR fairness review.',
  ),
  Q28: m('MERGE', 'T25', 'Dimensions describe the decision-maker’s persona, not the stakeholders.'),
  Q29: m('REBUILD', 'T20'),
  Q30: m(
    'CONTENT',
    'T20',
    'A library of standard decisions is a template set, not a paid diagnostic.',
  ),
  Q31: m('MERGE', 'T09', 'The roadmap sequencer does not measure decision capacity.'),
  Q32: m('MERGE', 'T35'),
  Q33: m('REBUILD', 'T35', 'Skill is measured from resolved predictions, not self-rated.'),
  Q34: m('CONTENT', 'T27', 'A technique library is reference content.'),
  Q35: m(
    'REBUILD',
    'T27',
    'Generic weighted scoring cannot pick a method; Cynefin and reversibility questions can.',
  ),
  Q36: m('MERGE', 'T19'),
  Q37: m(
    'RETIRE',
    '',
    'Name promises automation; it is four ratings. Routing and approvals belong in Workflows.',
  ),
  Q38: m('VIEW', 'T19'),
  Q39: m('MERGE', 'T14'),
  Q40: m('VIEW', ''),
  Q41: m('VIEW', ''),
  Q42: m('MERGE', 'T30', 'Learning from decisions is done with after-action reviews.'),
  Q43: m('REBUILD', 'T29', 'Dimensions are “Self-Awareness” etc.; a risk monitor needs the risks.'),
  Q44: m('KEEP', 'T18', 'Built properly against a published standard.'),
  Q45: m('RETIRE', '', 'Cannot generate insight from four ratings.'),
  Q46: m('MERGE', 'T22', 'Rename: not predictive; the futures and odds are the user’s.'),
  Q47: m('MERGE', 'T22'),
  Q48: m('MERGE', 'T25'),
  Q49: m('MERGE', 'T19', 'Rationale is a field in the decision record.'),
  Q50: m('MERGE', 'T35', 'There is no benchmark data to compare against.'),
  Q51: m('MERGE', 'T25'),
  Q52: m('MERGE', 'T26', 'Dimensions are already force-field forces.'),
  Q53: m('MERGE', 'T09', 'Dimensions are “decision energy”, not capacity or workload.'),
  Q54: m('MERGE', 'T19', 'Follow-through is measured from the register.'),
  Q55: m('MERGE', 'T19', 'Cycle time is computed from decision dates.'),
  Q56: m('MERGE', 'T23'),
  Q57: m('MERGE', 'T22', 'Money and time estimates go into the scenario calculator.'),
  Q58: m('REBUILD', 'T30', 'Needs claimed vs realised values.'),
  Q59: m('MERGE', 'T22', 'The scenario calculator already reports downside.'),
  Q60: m('MERGE', 'T23'),
  Q61: m('MERGE', 'T25', '“Everyone it touches” is a stakeholder map.'),
  Q62: m('VIEW', 'T19', 'A filter on the register.'),
  Q63: m('RETIRE', '', 'Dimensions (“Claimed Territory”) do not analyse markets.'),
  Q64: m('VIEW', 'T19'),
  Q65: m('VIEW', 'T19'),
  Q66: m('VIEW', 'T19'),
  Q67: m('RETIRE', '', 'Dimensions about societal contribution do not match its purpose.'),
  Q68: m('MERGE', 'T22'),
  Q69: m('MERGE', 'T19', 'The expected-value calculator cannot diagnose consistency over time.'),
  Q70: m('MERGE', 'T19'),
  Q71: m('MERGE', 'T19'),
  Q72: m('MERGE', 'T19', 'Dimensions (“Future Anxiety Distortion”) do not match a snapshot.'),
  Q73: m('MERGE', 'T19', 'Dependencies are a field in the register.'),
  Q74: m('MERGE', 'T19'),
  Q75: m('MERGE', 'T12'),
  Q76: m('REBUILD', 'T33', 'Needs the actual commitments and due dates.'),
  Q77: m('RETIRE', '', 'Nothing can raise an “alert” from four ratings; no recognised method.'),
  Q78: m('MERGE', 'T24'),
  Q79: m('MERGE', 'T23'),
  Q80: m('MERGE', 'T35', '“Is judgement improving?” is calibration measured over time.'),
  Q81: m('RETIRE', '', 'Generic; dimensions are about “decision identity”.'),
  Q82: m('CONTENT', 'T31', 'Written decision principles are a document, not a diagnostic.'),
  Q83: m('MERGE', 'T31'),
  Q84: m('MERGE', 'T31'),
  Q85: m('MERGE', 'T31', 'Dimensions do not match a health check.'),
  Q86: m('REBUILD', 'T36', 'Dimensions are about decision authority, not continuity.'),
  Q87: m('MERGE', 'T20'),
  Q88: m('VIEW', ''),
  Q89: m('MERGE', 'T01'),
  Q90: m('MERGE', 'T20', 'Dimensions about “identity” do not measure autonomy.'),
  Q91: m('MERGE', 'T32'),
  Q92: m('MERGE', 'T33'),
  Q93: m('MERGE', 'T32'),
  Q94: m('MERGE', 'T33', 'Dimensions (“Declaration Courage”) do not track commitments.'),
  Q95: m('MERGE', 'T04', 'A mandate is objectives per leader.'),
  Q96: m('CONTENT', 'T27'),
  Q97: m('MERGE', 'T34'),
  Q98: m('REBUILD', 'T20'),
  Q99: m('REBUILD', 'T32', 'Closest to a real standard already; anchor to ISO 37000 principles.'),
  Q100: m('RETIRE', '', 'Sign-off is an approval step in Workflows, not a diagnostic.'),

  X01: m('REBUILD', 'T29'),
  X02: m('REBUILD', 'T37'),
  X03: m('MERGE', 'T32'),
  X04: m('REBUILD', 'T34'),
  X05: m('REBUILD', 'T38'),
  X06: m('REBUILD', 'T39'),
  X07: m('MERGE', 'T36'),

  A02: m('KEEP', 'T40', 'Real calculation. Rename to “Skills Gap Analysis”.'),
  A03: m(
    'REBUILD',
    'T41',
    'Runs the roadmap sequencer; workforce planning is supply against demand.',
  ),
  A04: m('MERGE', 'T42'),
  A05: m('MERGE', 'T31'),
  A06: m('MERGE', 'T41'),
  A07: m('REBUILD', 'T43'),
  A08: m('MERGE', 'T43'),
  A09: m('REBUILD', 'T44'),
  A10: m('MERGE', 'T44'),
  A11: m('REBUILD', 'T45', 'Engagement has to come from staff answers, not one person’s rating.'),
  A12: m('MERGE', 'T45'),
  A13: m('MERGE', 'T45'),
  A14: m('MERGE', 'T43'),
  A15: m('MERGE', 'T46'),
  A16: m('MERGE', 'T47'),
  A17: m('MERGE', 'T46', 'Four separately paid “parts” of one programme.'),
  A18: m('MERGE', 'T46'),
  A19: m('MERGE', 'T46'),
  A20: m('MERGE', 'T46'),
  A21: m('MERGE', 'T42'),
  A22: m('KEEP', 'T42', 'Built properly.'),
  A23: m('REBUILD', 'T47'),
  A24: m('MERGE', 'T44'),
  A25: m(
    'KEEP',
    'T48',
    'Real calculation. Rename: it measures readiness; it does not generate pathways.',
  ),
  A26: m('MERGE', 'T41'),
  A27: m('MERGE', 'T45'),
  A28: m('MERGE', 'T42'),
  A29: m(
    'RETIRE',
    '',
    'Measures the product’s own module integration (“Cross-Module Alignment”), not the customer.',
  ),
  A30: m('MERGE', 'T14'),
  A31: m('MERGE', 'T43'),
  A32: m('VIEW', ''),

  Z01: m('REBUILD', 'T51', 'Dimensions are about AI integration, not opportunities.'),
  Z02: m('MERGE', 'T50'),
  Z03: m('MERGE', 'T50'),
  Z04: m('MERGE', 'T49'),
  Z05: m('MERGE', 'T02'),
  Z06: m('REBUILD', 'T50', 'A milestone tracker needs the milestones.'),
  Z07: m('RETIRE', '', 'No recognised method.'),
  Z08: m('VIEW', ''),
  Z09: m('MERGE', 'T02'),
  Z10: m('MERGE', 'T02'),
  Z11: m('MERGE', 'T06'),
  Z12: m('MERGE', 'T51'),
  Z13: m('MERGE', 'T30'),
  Z14: m('RETIRE', '', 'No recognised method.'),
  Z15: m('MERGE', 'T30'),

  P01: m('MERGE', 'T06'),
  P02: m('MERGE', 'T06'),
  P03: m('MERGE', 'T07'),
  P04: m('MERGE', 'T07'),
  P05: m('MERGE', 'T09'),
  P06: m('MERGE', 'T08'),
  P07: m('MERGE', 'T10'),
  P08: m('MERGE', 'T15'),
  P09: m('MERGE', 'T02'),
  P10: m('REBUILD', 'T13'),
  P11: m('MERGE', 'T13', 'There is no benchmark data to compare against.'),
  P12: m('MERGE', 'T06'),
  P13: m('MERGE', 'T06'),
  P14: m('KEEP', 'T10', 'Real calculation (Theory of Constraints).'),
  P15: m('VIEW', ''),
  P16: m('MERGE', 'T13'),
  P17: m('MERGE', 'T14'),
  P18: m('MERGE', 'T14'),
  P19: m('MERGE', 'T45'),
  P20: m('MERGE', 'T40'),
  P21: m('MERGE', 'T10', 'Duplicate of P14.'),
  P22: m('MERGE', 'T10', 'Same name as C02.'),
  P23: m('MERGE', 'T15'),
  P24: m('REBUILD', 'T15'),
  P25: m('REBUILD', 'T16'),
  P26: m('MERGE', 'T50'),
  P27: m('MERGE', 'T49'),
  P28: m('RETIRE', '', 'Dimensions are the product’s own module names (“CORE–GROW Convergence”).'),
  P29: m('MERGE', 'T08'),
  P30: m('MERGE', 'T06'),

  F01: m('KEEP', 'T56', 'Real calculation. Remove “real-time”: figures are typed in.'),
  F02: m(
    'REBUILD',
    'T57',
    'Calculates past periods only but promises forecasts and cash-flow projections.',
  ),
  F03: m('REBUILD', 'T58', 'P&L arithmetic does not link KPIs to their drivers.'),
  F04: m(
    'REBUILD',
    'T59',
    'Runs the process-bottleneck calculator; cost work needs spend analysis.',
  ),
  F05: m('REBUILD', 'T60', 'Its own disclosure says it “does not value the business”.'),
  F06: m('REBUILD', 'T61', 'P&L arithmetic cannot assess controls.'),
  F07: m('REBUILD', 'T62', 'P&L arithmetic cannot assess the finance function.'),

  G02: m('MERGE', 'T51'),
  G03: m('KEEP', 'T52', 'Built properly.'),
  G04: m('KEEP', 'T54', 'Built properly.'),
  G05: m('MERGE', 'T05'),
  G06: m('KEEP', 'T55', 'Keep, but add level descriptions so a rating means the same to everyone.'),
  G07: m('KEEP', 'T53', 'Built properly.'),
  G08: m(
    'RETIRE',
    '',
    'An internal view for advisers about an engagement, not a customer diagnostic.',
  ),
  G09: m('VIEW', ''),
};
