import PDFDocument from 'pdfkit';

const labels = {
  'proposal-drafter': 'Proposal',
  'scope-builder': 'Scope of Work',
  'sow-builder': 'Statement of Work',
  'brief-builder': 'Client Brief',
  'deliverable-builder': 'Deliverable Specification',
  'acceptance-builder': 'Acceptance Criteria',
  'change-order': 'Change Order',
  'quote-generator': 'Quote',
  'estimate-generator': 'Estimate',
  'invoice-generator': 'Invoice',
};

export function renderAgentRunPdf(run, workspace, signatures = []) {
  const output = JSON.parse(run.output || '{}');
  const doc = new PDFDocument({ margin: 50 });

  doc.fontSize(10).fillColor('#666').text('LAMID ONE', { continued: true }).text(`  ·  ${workspace.name}`, { align: 'left' });
  doc.moveDown(0.5);
  doc.fontSize(20).fillColor('#111').text(labels[run.agent_id] || run.agent_id);
  doc.fontSize(9).fillColor('#666').text(`Generated ${new Date(run.completed_at || run.created_at).toLocaleString()}`);
  doc.moveDown(1);

  doc.fontSize(11).fillColor('#111').text(output.response || '(no content)', { align: 'left' });
  doc.moveDown(1);

  if (output.evidence && typeof output.evidence === 'object') {
    doc.fontSize(12).fillColor('#111').text('Details', { underline: true });
    doc.moveDown(0.3);
    for (const [key, value] of Object.entries(output.evidence)) {
      if (value === null || value === undefined) continue;
      doc.fontSize(10).fillColor('#333').text(`${key}: ${value}`);
    }
    doc.moveDown(1);
  }

  if (signatures.length > 0) {
    doc.fontSize(12).fillColor('#111').text('Signatures (in-app attestation only)', { underline: true });
    doc.moveDown(0.3);
    for (const signature of signatures) {
      doc
        .fontSize(10)
        .fillColor(signature.valid ? '#333' : '#b00020')
        .text(
          `${signature.signer_name} — signed ${new Date(signature.signed_at).toLocaleString()}` +
            (signature.valid ? '' : ' (signature no longer matches this document)'),
        );
    }
    doc.moveDown(0.5);
    doc
      .fontSize(8)
      .fillColor('#999')
      .text('This is an in-app attestation (typed name + timestamp + content hash), not a qualified electronic signature.');
  }

  doc.moveDown(1.5);
  doc.fontSize(8).fillColor('#999').text(`Generated by LAMID ONE — ${run.agent_id} — run ${run.id}`);

  return doc;
}
