import PDFDocument from 'pdfkit';

const labels = {
  'proposal-drafter': 'Proposal',
  'scope-builder': 'Scope of Work',
  'sow-builder': 'Statement of Work',
  'brief-builder': 'Client Brief',
  'deliverable-builder': 'Deliverable Specification',
  'acceptance-builder': 'Acceptance Criteria',
  'change-order': 'Change Order',
  'contract-builder': 'Contract',
  'quote-generator': 'Quote',
  'estimate-generator': 'Estimate',
  'invoice-generator': 'Invoice',
};

// Documents that go to a client. Their body already carries every figure the reader needs;
// internal record IDs and the tool's method belong in the app, not on the client's copy.
const clientFacing = new Set(['invoice-generator']);

export function detailLines(run) {
  if (clientFacing.has(run.agent_id)) return [];
  const { evidence } = JSON.parse(run.output || '{}');
  if (!evidence || typeof evidence !== 'object') return [];
  return Object.entries(evidence)
    .filter(([, value]) => value !== null && value !== undefined)
    .map(([key, value]) => `${key}: ${value}`);
}

export function footerLine(run) {
  return clientFacing.has(run.agent_id)
    ? 'Generated with LAMID ONE'
    : `Generated by LAMID ONE — ${run.agent_id} — run ${run.id}`;
}

export function renderAgentRunPdf(run, workspace, signatures = []) {
  const output = JSON.parse(run.output || '{}');
  const doc = new PDFDocument({ margin: 50 });

  doc
    .fontSize(10)
    .fillColor('#666')
    .text('LAMID ONE', { continued: true })
    .text(`  ·  ${workspace.name}`, { align: 'left' });
  doc.moveDown(0.5);
  doc
    .fontSize(20)
    .fillColor('#111')
    .text(labels[run.agent_id] || run.agent_id);
  doc
    .fontSize(9)
    .fillColor('#666')
    .text(`Generated ${new Date(run.completed_at || run.created_at).toLocaleString()}`);
  doc.moveDown(1);

  doc
    .fontSize(11)
    .fillColor('#111')
    .text(output.response || '(no content)', { align: 'left' });
  doc.moveDown(1);

  const details = detailLines(run);
  if (details.length > 0) {
    doc.fontSize(12).fillColor('#111').text('Details', { underline: true });
    doc.moveDown(0.3);
    for (const line of details) doc.fontSize(10).fillColor('#333').text(line);
    doc.moveDown(1);
  }

  if (signatures.length > 0) {
    doc
      .fontSize(12)
      .fillColor('#111')
      .text('Signatures (in-app attestation only)', { underline: true });
    doc.moveDown(0.3);
    for (const signature of signatures) {
      doc
        .fontSize(10)
        .fillColor(signature.valid ? '#333' : '#b00020')
        .text(
          `${signature.signer_name} — signed ${new Date(signature.signed_at).toLocaleString()}` +
            (signature.valid ? '' : ' (signature no longer matches this document)'),
        );
    }
    doc.moveDown(0.5);
    doc
      .fontSize(8)
      .fillColor('#999')
      .text(
        'This is an in-app attestation (typed name + timestamp + content hash), not a qualified electronic signature.',
      );
  }

  doc.moveDown(1.5);
  doc
    .fontSize(8)
    .fillColor('#999')
    .text(footerLine(run));

  return doc;
}

// Only issued once a project has actually reached its terminal, fully-paid state (see
// requireClosedProject in projects.mjs) — this certifies delivered and paid work, not merely
// "the client clicked close."
export function renderProjectCertificatePdf(project, workspace, milestones) {
  const doc = new PDFDocument({ margin: 50 });

  doc
    .fontSize(10)
    .fillColor('#666')
    .text('LAMID ONE', { continued: true })
    .text(`  ·  ${workspace.name}`, { align: 'left' });
  doc.moveDown(0.5);
  doc.fontSize(20).fillColor('#111').text('Completion Certificate');
  doc.fontSize(9).fillColor('#666').text(`Issued ${new Date().toLocaleString()}`);
  doc.moveDown(1);

  doc.fontSize(14).fillColor('#111').text(project.title);
  doc.moveDown(0.5);
  doc
    .fontSize(11)
    .fillColor('#111')
    .text(
      `This certifies that all ${milestones.length} milestone(s) on this project were submitted, verified, approved and paid in full.`,
    );
  doc.moveDown(1);

  doc.fontSize(12).fillColor('#111').text('Milestones', { underline: true });
  doc.moveDown(0.3);
  for (const milestone of milestones) {
    doc
      .fontSize(10)
      .fillColor('#333')
      .text(`${milestone.title} — ${milestone.amount} ${milestone.currency} — paid`);
  }

  doc.moveDown(1.5);
  doc
    .fontSize(8)
    .fillColor('#999')
    .text(`Generated by LAMID ONE — project ${project.id}`);

  return doc;
}
