import fs from 'node:fs';
const file = 'src/app/app.mjs';
let s = fs.readFileSync(file, 'utf8').replaceAll('\r\n', '\n');
s = s.replace('import { openStore, hashPassword, verifyPassword, seedWorkspace }', 'import { openStore, verifyPassword }');
s = s.replace("import express from 'express';", "import express from 'express';\nimport { mountAccounts } from './accounts.mjs';");
s = s.replace('const tokenLifetime = 30 * 60 * 1000;\n', '');
s = s.replace('  production = false,', '  production = false,\n  mailProvider,\n  securityKey,\n  publicOrigin,');
const start = s.indexOf('  const issueAccountToken = ');
const end = s.indexOf("  app.use('/api', (req, res, next) => {\n    const token =", start);
if (start < 0 || end < 0) throw Error('auth boundaries missing');
s = s.slice(0, start) + `  app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
  const accounts = mountAccounts(app, store, { production, session, contexts, enterpriseMemberLimit, mailProvider, securityKey, publicOrigin });
` + s.slice(end);
s = s.replace("secure: production && process.env.COOKIE_SECURE === 'true'", 'secure: production');
s = s.replace('...limits.api,', "...limits.api, namespace: 'api',").replace('...limits.auth,', "...limits.auth, namespace: 'auth',").replace('...limits.mutation,', "...limits.mutation, namespace: 'mutation',").replace('...rateLimits.spend,', "...rateLimits.spend, namespace: 'spend',");
s = s.replace('return { app, store, runtime };', 'return { app, store, runtime, agentRuntime, mail: accounts.mail };');
fs.writeFileSync(file, s);
